### ISSUE TITLE
Tracking possible breaking changes

### ISSUE THREAD

**Issue by cuviper** [rust-num/num#147]
Since `num` is widely used, we should only sparingly bump semver, but when we do we should batch breaking changes together.

This is a place to track changes that we *might* make.  These may be API changes that would break existing users, of course, but also changes that would require us to increase the minimum Rust version.  Inclusion on this list does not guarantee we will do it, and exclusion probably just means it wasn't considered yet.  (If the need arises, we can also explicitly list changes we *won't* make.)

#### Proposed breaking changes

- [ ] #155 Hide `bigint` implementation details, basically removing `BigDigit` from the public interface.
- [ ] #59 Add type parameters to Checked traits.
- [ ] #80 Change `PrimInt` shifting bounds from `RHS=usize` to `u32`, for consistency with its methods.
- [ ] #118 next_after for Float (still unstable!)
- [ ] #126 Use/extend std versions of `Zero` and `One` (still unstable!)
- [ ] #153 Use `Mul` by reference in `num::pow`.

**Comment by cuviper** [comment]
Is this tracker actually useful?  I don't really like that GitHub doesn't show any change history when I edit the list.  Maybe we should just have a breaking-change label instead.

**Comment by hauleth** [comment]
I think labels is good idea.

**Comment by cuviper** [comment]
Alright, the issues above have labels now.
