### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by cuviper** [rust-num/num#357]
See #281, and this was previously in the next branch after #305.

- [x] rust-num/num-bigint#9
- [x] rust-num/num-complex#8
- [x] rust-num/num-rational#9

**Comment by CAD97** [comment]
Now that rust-num/num-rational#9 is closed, do we have an estimated timeline for when we can expect to see a num v0.2.0 (pre)release with serde1 support?

At current, it is possible to monkey-patch together a num 0.2-git by adding a git dependency on the three 

Scanning the num reexports, I spot the following issues marked with a 0.2 milestone:

- tagged [breaking change]
  - [ ] [num] [Missing default-features = false for bigint dependency](https://github.com/rust-num/num/issues/298)
  - [ ] [bigint] [Hide bigint implementation details](https://github.com/rust-num/num-bigint/issues/3)
  - [ ] [complex] [Make std a feature, using `#![no_std]` otherwise](https://github.com/rust-num/num-complex/issues/6)

- not tagged [breaking change]
  - [ ] [bigint] [Support the assignment operators for BigInt](https://github.com/rust-num/num-bigint/issues/7) [help wanted]

**Comment by cuviper** [comment]
Thanks for the summary -- there's really not much left!  I don't have a schedule, but I'll try to wrap this up soon.  Looking at your list:

- `num` will need to clean up all its features to match the updated sub-crates.
- `num-bigint` details: I already made the error type opaque, just want to remove `big_digit::*` from the public API.
- `num-complex` no-std had a PR that stalled.  I may just add the `std` feature with all functionality masked without it for now, then proper no-std support can come later.
- `BigInt` assign ops don't *have* to be done for 0.2.0 either, but it would be nice.

**Comment by cuviper** [comment]
> num-complex no-std had a PR that stalled. I may just add the std feature with all functionality masked without it for now, then proper no-std support can come later.

Hmm, it's not that easy to defer, because some no-std features will need to switch to `FloatCore`, and we can't change that in the API later.

**Comment by cuviper** [comment]
> Is there a reason Float doesn't have FloatCore as a "supertrait"? I realize that changing that would break semver-compatibility in num-traits, so is pretty much a non-option,

That's exactly the reason this wasn't done.

> The easy step is just to get the repository in 0.2.0-git mode,

You mean for `num` itself, pointing to the existing 0.2.0-git of sub-crates?  I actually did start that on my own branch here: https://github.com/cuviper/num/tree/release-0.2.0

**Comment by BelfordZ** [comment]
Any ETA on this? Trying to plan out some feature development around this.

**Comment by cuviper** [comment]
Just need to finish release notes in #367, hopefully in the next day or so.  If you want to kick the tires on that, it would be greatly appreciated!

**Comment by BelfordZ** [comment]
Thank you greatly @cuviper :) :)
